// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: integration/proto/message_with_option.proto

package proto

import (
	driver "database/sql/driver"
	json "encoding/json"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/travisjeffery/proto-go-sql"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (t *MessageWithOption) Scan(val interface{}) error {
	return json.Unmarshal(val.([]byte), t)
}

func (t *MessageWithOption) Value() (driver.Value, error) {
	return json.Marshal(t)
}
