// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: person.proto

package person

import (
	driver "database/sql/driver"
	json "encoding/json"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/travisjeffery/proto-go-sql"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (t *Person) Scan(val interface{}) error {
	valRaw := val.([]byte)
	valCopy := make([]byte, len(valRaw))
	copy(valCopy, valRaw)
	return json.Unmarshal(valCopy, t)
}

func (t *Person) Value() (driver.Value, error) {
	return json.Marshal(t)
}
